build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64:  "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  armv7:  "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"

labels:
  org.opencontainers.image.title: "Hikvision Event Listener"
  org.opencontainers.image.description: "Hikvision ISAPI alert listener for Home Assistant"
  org.opencontainers.image.license: "MIT"
