build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-addon-base-python:3.12"
  amd64: "ghcr.io/home-assistant/amd64-addon-base-python:3.12"
  armv7: "ghcr.io/home-assistant/armv7-addon-base-python:3.12"

labels:
  org.opencontainers.image.title: "Hikvision Event Listener"
  org.opencontainers.image.description: "Hikvision ISAPI alert listener for Home Assistant"
  org.opencontainers.image.license: "MIT"
