ARG BUILD_FROM=ghcr.io/home-assistant/${ARCH}-base:3.18
FROM $BUILD_FROM

# Install Python
RUN apk add --no-cache python3 py3-pip

# Install dependencies
RUN pip3 install requests

WORKDIR /app

COPY run.sh /app/run.sh
COPY hikvision_event_listener.py /app/hikvision_event_listener.py

RUN chmod +x /app/run.sh

CMD ["/app/run.sh"]
